# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-22 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='password',
            field=models.CharField(default='123456', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='123456', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='zipcode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
