# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-22 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190422_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='section_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
