# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-23 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190423_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sections')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student')),
            ],
        ),
    ]
